#Should player inventories be overwritten when restored?
overwrite-inventory: true

#Should the saved inventory be deleted after restored?
delete-after-restore: true

#Should restoring a single item remove it from the saved inventory?
delete-item-after-restore: true